# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false
env:
  global:
    - CODECOV_TOKEN="33a8fac8-8cd9-4b80-9d05-54bc38ef7f22"
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.ru.job4j.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - tel.89194491005@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

